import { useState } from 'react'
import { AlertDialog, Badge, Button, Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, ComboRow, CopyButton, Dialog, EmptyState, EntryRow, FeaturePage, Input, Label, MobileSubNav, NumberInput, PageHeader, Pagination, PreferencesColumns, PreferencesGroup, PreferencesGroups, ReloadButton, Row, SaveButton, SectionLabel, SectionNav, Segmented, Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue, Separator, Sheet, Spinner, StateChip, StatusChip, Switch, SwitchRow, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tabs, TagInput, Textarea, Toaster, useTheme } from '@chevalrouting/cheval-ui'
import { TimeSeriesChart } from '@chevalrouting/cheval-ui/charts'
import { TerminalPane } from '@chevalrouting/cheval-ui/terminal'
import { Box, Component, Globe, LayoutDashboard, Moon, Network, Route, Server, Shield, Sun } from 'lucide-react'
import { SharedComponents } from './SharedComponents'
import { ApplicationPatternComponents } from './ApplicationPatternComponents'

type Section = 'shared' | 'foundations' | 'forms' | 'surfaces' | 'feedback' | 'data' | 'preferences' | 'navigation' | 'patterns' | 'specialized'
const sections: { key: Section; label: string }[] = [{ key: 'shared', label: 'Shared components' }, { key: 'foundations', label: 'Foundations' }, { key: 'forms', label: 'Forms' }, { key: 'surfaces', label: 'Surface audit' }, { key: 'feedback', label: 'Feedback' }, { key: 'data', label: 'Data display' }, { key: 'preferences', label: 'Preferences' }, { key: 'navigation', label: 'Navigation' }, { key: 'patterns', label: 'Application patterns' }, { key: 'specialized', label: 'Specialized' }]

function ComponentExample({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card>
}

export default function App() {
  const [section, setSection] = useState<Section>('foundations')
  const [mode, setMode] = useState('automatic')
  const [enabled, setEnabled] = useState(true)
  const [count, setCount] = useState(3)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [alertOpen, setAlertOpen] = useState(false)
  const [sheetOpen, setSheetOpen] = useState(false)
  const [tags, setTags] = useState(['network', 'routing'])
  const [page, setPage] = useState(0)
  const [navSection, setNavSection] = useState('general')
  const { theme, toggle } = useTheme()
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 bg-background/90 backdrop-blur"><div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-5"><div className="flex items-center gap-2"><Component className="h-5 w-5 text-primary"/><span className="font-semibold">Cheval UI Workbench</span></div><Button variant="ghost" size="icon" aria-label="Toggle theme" title="Toggle theme" onClick={toggle}>{theme === 'dark' ? <Sun className="h-4 w-4"/> : <Moon className="h-4 w-4"/>}</Button></div></header>
    <main className="mx-auto max-w-7xl space-y-8 p-5 md:p-8"><PageHeader title="Component workbench" description="Interactive component examples imported through the public cheval-ui package surface." action={<Badge variant="secondary">{__CHEVAL_UI_VERSION__}</Badge>}/><Tabs label="Workbench sections" tabs={sections} active={section} onChange={setSection} variant="pills" className="flex-wrap overflow-visible bg-transparent p-0"/>
      {section === 'foundations' && <div className="grid gap-5 lg:grid-cols-2"><ComponentExample title="Buttons" description="Adwaita action hierarchy and states."><div className="flex flex-wrap gap-2"><Button>Default</Button><Button variant="suggested">Suggested</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="destructive">Destructive</Button><Button disabled>Disabled</Button></div></ComponentExample><ComponentExample title="Badges and status" description="Metadata and operational state."><div className="flex flex-wrap gap-2"><Badge>Default</Badge><Badge variant="outline">Outline</Badge><StatusChip intent="success" label="Healthy" pulse/><StatusChip intent="warning" label="Degraded"/><StateChip state="ESTABLISHED"/></div></ComponentExample><ComponentExample title="Tabs" description="Pill navigation variant."><Tabs tabs={sections} active={section} onChange={setSection} variant="pills"/></ComponentExample><ComponentExample title="Async actions" description="Loading and action indicators."><div className="flex items-center gap-4"><Spinner size="sm" className="h-auto"/><ReloadButton onClick={() => undefined}/><SaveButton isDirty saving={false} onClick={() => undefined}/></div></ComponentExample></div>}
      {section === 'forms' && <div className="grid gap-5 lg:grid-cols-2"><ComponentExample title="Text fields" description="Inputs and text areas."><div className="space-y-4"><div className="space-y-1"><Label htmlFor="name">Name</Label><Input id="name" defaultValue="edge-router-01"/></div><div className="space-y-1"><Label htmlFor="description">Description</Label><Textarea id="description" placeholder="Optional context"/></div><TagInput values={tags} onChange={setTags} suggestions={['firewall', 'monitoring']} /></div></ComponentExample><ComponentExample title="Choices" description="Selection controls."><div className="space-y-4"><Segmented value={mode} onChange={setMode} options={[{ value: 'automatic', label: 'Automatic' }, { value: 'manual', label: 'Manual' }]}/><Select defaultValue="stable"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectLabel>Release channel</SelectLabel><SelectItem value="stable">Stable</SelectItem><SelectItem value="preview">Preview</SelectItem></SelectGroup></SelectContent></Select><div className="flex items-center justify-between px-1 py-2"><Label htmlFor="enabled">Enabled</Label><Switch id="enabled" checked={enabled} onCheckedChange={setEnabled}/></div><NumberInput value={count} onChange={(value) => setCount(value ?? 0)} min={0}/></div></ComponentExample></div>}
      {section === 'surfaces' && <div className="grid gap-5 lg:grid-cols-2"><ComponentExample title="Select controls" description="Trigger, disabled state, grouped menu, and menu separator."><div className="space-y-3"><Select defaultValue="automatic"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectLabel>Operation mode</SelectLabel><SelectItem value="automatic">Automatic</SelectItem><SelectItem value="manual">Manual</SelectItem></SelectGroup><SelectSeparator/><SelectGroup><SelectLabel>Diagnostics</SelectLabel><SelectItem value="safe">Safe mode</SelectItem></SelectGroup></SelectContent></Select><Select defaultValue="edge"><SelectTrigger className="h-8"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="edge">Edge router</SelectItem><SelectItem value="core">Core router</SelectItem></SelectContent></Select><Select disabled><SelectTrigger><SelectValue placeholder="Disabled select"/></SelectTrigger><SelectContent><SelectItem value="disabled">Disabled</SelectItem></SelectContent></Select></div></ComponentExample><ComponentExample title="Card anatomy" description="Elevated surface with header, content, footer, and no explicit frame."><Card className="bg-background"><CardHeader><CardTitle>Router status</CardTitle><CardDescription>Shared card composition</CardDescription></CardHeader><CardContent><div className="flex items-center justify-between"><span className="text-sm">Control plane</span><StatusChip intent="success" label="Healthy"/></div></CardContent><CardFooter className="justify-end gap-2"><Button variant="ghost">Dismiss</Button><Button>Inspect</Button></CardFooter></Card></ComponentExample><ComponentExample title="Field and action edges" description="Compare control depth without bright outlines."><div className="space-y-3"><Input defaultValue="192.0.2.1"/><Textarea defaultValue="No persistent white frame should appear."/><div className="flex flex-wrap gap-2"><Button variant="outline">Outline action</Button><Button variant="secondary">Secondary action</Button><ReloadButton onClick={() => undefined}/></div></div></ComponentExample><ComponentExample title="Boxed rows" description="Adwaita-style grouped surface and internal row separator."><PreferencesGroup><EntryRow title="Hostname" defaultValue="edge-router-01"/><SwitchRow title="Enabled" checked={enabled} onCheckedChange={setEnabled}/><Row title="State"><Badge variant="success">Ready</Badge></Row></PreferencesGroup></ComponentExample></div>}
      {section === 'feedback' && <div className="grid gap-5 lg:grid-cols-2"><ComponentExample title="Dialogs and sheets" description="Focused confirmation and editing workflows."><div className="flex flex-wrap gap-2"><Button onClick={() => setDialogOpen(true)}>Open dialog</Button><Button variant="outline" onClick={() => setAlertOpen(true)}>Open alert</Button><Button variant="secondary" onClick={() => setSheetOpen(true)}>Open sheet</Button></div><Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} title="Apply changes?" description="This is rendered from the package dialog composition." footer={<><Button variant="outline" onClick={() => setDialogOpen(false)}>Cancel</Button><Button variant="suggested" onClick={() => setDialogOpen(false)}>Apply</Button></>}/><AlertDialog open={alertOpen} onCancel={() => setAlertOpen(false)} onConfirm={() => setAlertOpen(false)} title="Delete item?" description="This action cannot be undone." confirmLabel="Delete" destructive/><Sheet open={sheetOpen} onClose={() => setSheetOpen(false)} title="Edit component"><EntryRow title="Name" defaultValue="Component"/><Button variant="suggested" onClick={() => setSheetOpen(false)}>Save</Button></Sheet></ComponentExample><ComponentExample title="Empty state" description="Guidance for empty collections."><EmptyState icon={<Box/>} title="Nothing here yet" message="Create the first item to get started."/></ComponentExample><ComponentExample title="Labels and separators" description="Low-emphasis structure and copy actions."><div className="space-y-3"><SectionLabel>Connection details</SectionLabel><Separator/><div className="flex items-center gap-2 font-mono text-sm">192.0.2.4<CopyButton text="192.0.2.4"/></div></div></ComponentExample></div>}
      {section === 'data' && <ComponentExample title="Table" description="Structured data with semantic status."><Table><TableHeader><TableRow><TableHead>Component</TableHead><TableHead>Category</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{[['Button','Primitive','STABLE'],['AppShell','Layout','ACTIVE'],['TimeSeriesChart','Chart','PREVIEW']].map(([name, category, status]) => <TableRow key={name}><TableCell className="font-medium">{name}</TableCell><TableCell>{category}</TableCell><TableCell><StateChip state={status}/></TableCell></TableRow>)}</TableBody></Table></ComponentExample>}
      {section === 'data' && <Pagination page={page} totalPages={4} total={38} pageSize={10} onPage={setPage} unit="components"/>}
      {section === 'preferences' && <div className="space-y-6"><PreferencesGroups><PreferencesGroup title="General" description="Rows, entries, and switches."><EntryRow title="Hostname" defaultValue="edge-router-01"/><SwitchRow title="Monitoring" subtitle="Collect operational metrics" checked={enabled} onCheckedChange={setEnabled}/><Row title="Version" subtitle="Current package release"><Badge>{__CHEVAL_UI_VERSION__}</Badge></Row></PreferencesGroup><PreferencesGroup title="Advanced"><ComboRow title="Mode"><Select defaultValue="automatic"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="automatic">Automatic</SelectItem></SelectContent></Select></ComboRow></PreferencesGroup></PreferencesGroups><PreferencesColumns title="Columns"><PreferencesGroup><EntryRow title="Address" defaultValue="192.0.2.4"/></PreferencesGroup><PreferencesGroup><EntryRow title="Gateway" defaultValue="192.0.2.254"/></PreferencesGroup></PreferencesColumns></div>}
      {section === 'navigation' && <div className="grid gap-5 lg:grid-cols-2"><ComponentExample title="Section navigation" description="Responsive navigation for feature subsections."><SectionNav items={[{ key: 'general', label: 'General' }, { key: 'advanced', label: 'Advanced', badge: 2 }]} active={navSection} onChange={setNavSection}><div className="rounded-lg bg-muted/40 p-5 text-sm">{navSection === 'general' ? 'General settings' : 'Advanced settings'}</div></SectionNav></ComponentExample><ComponentExample title="Feature page" description="Status and configuration framing."><FeaturePage title="DNS" renderStatus={<StateChip state="RUNNING"/>} renderConfig={(setAction) => <Button onClick={() => setAction(<SaveButton isDirty saving={false} onClick={() => undefined}/>)}>Register action</Button>}/></ComponentExample><ComponentExample title="Mobile sub navigation" description="Scrollable sub page pills for the bottom tab bar. The current page stays highlighted."><div className="rounded-lg bg-sidebar"><MobileSubNav items={[{ to: '/', label: 'Dashboard', icon: LayoutDashboard, exact: true }, { to: '/interfaces', label: 'Interfaces', icon: Network }, { to: '/routing', label: 'Routing', icon: Route }, { to: '/dns', label: 'DNS', icon: Globe }, { to: '/firewall', label: 'Firewall', icon: Shield }]}/></div></ComponentExample></div>}
      {section === 'shared' && <SharedComponents />}
      {section === 'patterns' && <ApplicationPatternComponents />}
      {section === 'specialized' && <div className="space-y-5"><ComponentExample title="Time series chart" description="Shared monitoring visualization."><TimeSeriesChart height={220} data={Array.from({ length: 12 }, (_, index) => ({ ts: Math.floor(Date.now() / 1000) - (11 - index) * 60, rx: 20 + index * 4, tx: 56 - index * 2 }))} series={[{ dataKey: 'rx', label: 'Receive', color: 'hsl(var(--chart-1))' }, { dataKey: 'tx', label: 'Transmit', color: 'hsl(var(--chart-2))' }]}/></ComponentExample><ComponentExample title="Terminal pane" description="Shared terminal surface. This component example intentionally has no backend session."><div className="h-52 overflow-hidden rounded-lg"><TerminalPane wsPath="/__cheval_ui_terminal_component_example" quiet/></div></ComponentExample></div>}
    </main>
    <Toaster theme={theme}/>
  </div>
}
