import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.getByRole('tablist', { name: 'Workbench sections' }).getByRole('tab', { name: 'Shared components', exact: true }).click()
})

test('integer edits reject partial numbers and invalid ranges before submitting', async ({ page }) => {
  const field = page.getByLabel('Workers', { exact: true })
  for (const invalid of ['', '2abc', '2.5', '0', '17', '9007199254740992']) {
    await field.fill(invalid)
    await page.getByRole('button', { name: 'Save example', exact: true }).click()
    await expect(page.getByText('Not submitted', { exact: true })).toBeVisible()
    await expect(field).toHaveAttribute('aria-invalid', 'true')
    expect(await field.evaluate((input: HTMLInputElement) => input.checkValidity())).toBe(false)
  }
  await field.fill('04')
  await expect(field).toHaveValue('04')
  await page.getByRole('button', { name: 'Save example', exact: true }).click()
  await expect(page.getByText('Saved 4 workers')).toBeVisible()
  await field.fill('bad')
  await page.getByRole('button', { name: 'Reset example' }).click()
  await expect(field).toHaveValue('2')
  expect(await field.evaluate((input: HTMLInputElement) => input.checkValidity())).toBe(true)
})

test('choice row supports empty values and disabled options', async ({ page }) => {
  const choice = page.getByRole('combobox', { name: 'Strategy' })
  await choice.click()
  await expect(page.getByRole('option', { name: 'Unavailable', exact: true })).toHaveAttribute('aria-disabled', 'true')
  await page.getByRole('option', { name: 'Manual', exact: true }).click()
  await expect(choice).toHaveText('Manual')
  await choice.click()
  await page.getByRole('option', { name: 'Automatic', exact: true }).click()
  await expect(choice).toHaveText('Automatic')
  await expect(page.getByRole('combobox', { name: 'Disabled choice' })).toBeDisabled()
})

test('split menu skips disabled actions and restores focus', async ({ page }) => {
  const trigger = page.getByRole('button', { name: 'More actions', exact: true })
  await trigger.focus()
  await trigger.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Clone example' })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Import example' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByText('Imported', { exact: true })).toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.press('ArrowUp')
  await expect(page.getByRole('menuitem', { name: 'Configure example' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await trigger.click()
  await page.getByRole('menuitem', { name: 'Configure example' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('button', { name: 'Busy example' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Disabled example' })).toBeDisabled()
})

test('variable picker selects by keyboard and pointer without blur races', async ({ page }) => {
  const field = page.getByRole('combobox', { name: 'Variable or literal value' })
  await field.fill('literal')
  await expect(page.getByRole('option')).toHaveCount(3)
  await field.press('ArrowDown')
  await field.press('Enter')
  await expect(field).toHaveValue('$region')
  await field.fill('something else')
  await page.getByRole('option', { name: '$instance' }).click()
  await expect(field).toHaveValue('$instance')
  await field.fill('unchanged')
  await field.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(field).toHaveValue('unchanged')
  await expect(field).toBeFocused()
})

test('display, retry, disclosure, and theme states fit the viewport', async ({ page }, testInfo) => {
  await expect(page.getByRole('meter', { name: 'Storage used' })).toHaveAttribute('aria-valuenow', '58')
  await expect(page.getByRole('meter', { name: 'Clamped example' })).toHaveAttribute('aria-valuenow', '100')
  await expect(page.getByText('null', { exact: true })).toBeVisible()
  await expect(page.getByText('"workers": 4', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByText('Examples are up to date.')).toBeVisible()
  await page.getByRole('button', { name: 'Show loading' }).click()
  await expect(page.getByText('Loading examples…')).toBeVisible()
  for (let theme = 0; theme < 2; theme++) {
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: testInfo.outputPath(`shared-${theme === 0 ? 'dark' : 'light'}.png`), fullPage: true, animations: 'disabled' })
    await page.getByRole('button', { name: 'Toggle theme' }).click()
  }
})

test('portaled controls remain usable within a modal dialog', async ({ page }) => {
  await page.getByRole('button', { name: 'Show dialog controls' }).click()
  const dialog = page.getByRole('dialog')
  const field = dialog.getByRole('combobox', { name: 'Dialog variable' })
  await field.fill('free text')
  await page.getByRole('option', { name: '$region' }).click()
  await expect(field).toHaveValue('$region')
  await expect(dialog).toBeVisible()
  const trigger = dialog.getByRole('button', { name: 'Dialog alternate actions' })
  await trigger.click()
  await page.getByRole('menuitem', { name: 'Dialog alternate', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(trigger).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})
